version: '3.7'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    ports:
      - "8089:8080"
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - KEYCLOAK_HTTP_PORT=8080
    restart: always
    networks:
      - keycloak-network

networks:
  keycloak-network:
    driver: bridge
