server:
  port: 8087
  servlet:
    context-path: /api

spring:
  application:
    name: gym-api-gateway

  cloud:
    gateway:
      routes:
        - id: clases-service
          uri: lb://clases-service
          predicates:
            - Path=/clase/**
        - id: entrenadores-service
          uri: lb://microservicio-entrenador
          predicates:
            - Path=/entrenador/**
        - id: miembros-service
          uri: lb://microservicio-miembro
          predicates:
            - Path=/miembros/**
        - id: equipamientos-service
          uri: lb://equipment-service
          predicates:
            - Path=/equipos/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
